/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VideoBehaviourSurvey {
        "bootupText": string;
        "bootupTime": any;
        "challengeAnswerTime": any;
        "challengeDescriptionText": string;
        "challengeFailText": string;
        "challengeInterval": any;
        "challengeSuccessText": string;
        "end": any;
        "exitSleepModeKey": string;
        "sleepModeText": string;
        "start": any;
        "timeOverText": string;
        "timeout": any;
        "videoHeight": any;
        "videoId": any;
        "videoWidth": any;
    }
}
declare global {
    interface HTMLVideoBehaviourSurveyElement extends Components.VideoBehaviourSurvey, HTMLStencilElement {
    }
    var HTMLVideoBehaviourSurveyElement: {
        prototype: HTMLVideoBehaviourSurveyElement;
        new (): HTMLVideoBehaviourSurveyElement;
    };
    interface HTMLElementTagNameMap {
        "video-behaviour-survey": HTMLVideoBehaviourSurveyElement;
    }
}
declare namespace LocalJSX {
    interface VideoBehaviourSurvey {
        "bootupText"?: string;
        "bootupTime"?: any;
        "challengeAnswerTime"?: any;
        "challengeDescriptionText"?: string;
        "challengeFailText"?: string;
        "challengeInterval"?: any;
        "challengeSuccessText"?: string;
        "end"?: any;
        "exitSleepModeKey"?: string;
        "sleepModeText"?: string;
        "start"?: any;
        "timeOverText"?: string;
        "timeout"?: any;
        "videoHeight"?: any;
        "videoId"?: any;
        "videoWidth"?: any;
    }
    interface IntrinsicElements {
        "video-behaviour-survey": VideoBehaviourSurvey;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "video-behaviour-survey": LocalJSX.VideoBehaviourSurvey & JSXBase.HTMLAttributes<HTMLVideoBehaviourSurveyElement>;
        }
    }
}
